services:
  - type: web
    name: laudspeaker
    healthCheckPath: /login
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: PORT
        value: 80
      - key: MONGOOSE_URL
        fromService:
          type: pserv
          name: mongo
          property: hostport
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: clickhouse
          property: hostport
      - key: REDIS_HOST
        fromService:
          type: redis
          name: laudspeaker
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: laudspeaker
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: laudspeaker-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: laudspeaker-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: laudspeaker-db
          property: host
      - key: DATABASE_NAME
        fromDatabase:
          name: laudspeaker-db
          property: database
  - type: redis
    name: laudspeaker
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: pserv
    name: clickhouse
    env: docker
    dockerfilePath: ./Dockerfile.clickhouse
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
  - type: pserv
    name: mongo
    env: docker
    dockerfilePath: ./Dockerfile.mongo
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
databases:
- name: laudspeaker-db
